[package]
name = "rust_piston_practice"
version = "0.1.0"

[dependencies]
piston = "1.0.0"
piston2d-graphics = "0.44.0"
pistoncore-glutin_window = "0.72.0"
piston2d-opengl_graphics = "0.85.0"
rand = "0.8"
